### PR TITLE
Logica Fix

### PR DESCRIPTION
**Pull request by plarocque4**
Fix the auth_response by changing the patient to the patientId as it should be.
Coordinate this fix with the updates to crd-request-generator and test-ehr.

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
looks good, are the scopes changed as well?

**Comment by plarocque4** [comment]
> looks good, are the scopes changed as well?

I did not change the scopes. I thought that you had said you were going to look into a better fix other than just removing scope down to just launch.

**Comment by KeeyanGhoreshi** [comment]
right, I looked into it, my initial thought was correct, the scopes just have to match between the ones we ask for and the ones the DTR app is authorized for.  The issue seemed to just be that the scopes on logica don't allow the wildcard, so `patient/*.*` didn't work, which is why we were getting the scope error.

**Comment by plarocque4** [comment]
If that's the case, do you have a solution to what we should set the scopes to?

**Comment by KeeyanGhoreshi** [comment]
For now I just set them to be the same as what we ask for in DTR: 

`user/Observation.read patient/Patient.read patient/Coverage.read user/Patient.read patient/Condition.read patient/Observation.read launch user/Practitioner.read`

**Comment by plarocque4** [comment]
Could you push those scope changes up into this branch?

**Review by KeeyanGhoreshi — APPROVED** [review]

**Pull request merged**
