### PR TITLE
Changes needed to get the connectathon branch to run on LogicaHealth servers

### PR DESCRIPTION
**Pull request by plarocque4**

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
what was the issue causing it not to run?

**Comment by plarocque4** [comment]
> what was the issue causing it not to run?

There seemed to be two issues, running the alpine version instead of slim along with not enough resources on the server caused it to timeout building. I probably should try running without the change to slim and see if it was just the resource issue before we push this in.

**Comment by plarocque4** [comment]
Yes, but unfortunately your changes still weren't enough to actually get it to run. This was the result of a late night before the connectathon trying to get it to work.

**Comment by KeeyanGhoreshi** [comment]
If it's not the version of node, then I'd be interested in figuring out what is the root cause of the failure.  Adding the progress bar worked for me as well when docker was failing previously, but it was only because it would stop the process from timing out.  I had thought npm-run-all was why the process was being allowed to time out and continue without finishing but I suppose I was mistaken.

**Comment by plarocque4** [comment]
I'm pretty sure the thing that helped the most was giving it more memory.

**Comment by plarocque4** [comment]
I switched back to master and it still works with more resources on the davinci server. I'm going to close this pull request.

**Pull request closed without merging**
