### PR TITLE
fix windows 10

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
should fix the bug on windows 10 where the json server does not start.  Tested on a windows 10 machine.

### CODE REVIEW

**Comment by lpdecelles** [comment]
image

I am seeing this (above) error when I try to start it.

**Comment by yuliumitre** [comment]
I got the same error as Larry when tried to start dtr.

**Comment by KeeyanGhoreshi** [comment]
did you install?  The npm-run-all package is new

**Review by yuliumitre — APPROVED** [review]
npm install does help. The DTR app loads and works well on Mac.

**Pull request merged**
