### PR TITLE
759 Remove empty answer or item from QuestionnaireResponse

### PR DESCRIPTION
**Pull request by yunwwang**
Changes in PR includes:
1) rename variable dynamic_choice_only to saved_response to clarify the purpose for this variable is to indicate if response_items are from saved Questionnaire.
2) remove empty answer array and item array from a QuestionnaireResponse item
3) Add QuestionnaireResponse item to response_items array if the item has answer(s) or child item(s)

### CODE REVIEW

**Comment by lpdecelles** [comment]
Yunwei, does this also fix https://jira.mitre.org/browse/DMEERX-658?

**Comment by lpdecelles** [comment]
Yunwei, is there a good way to test this?

**Comment by yunwwang** [comment]
This fixes a tooling/logging issue. It has no effect on the actual functionality. When DTR load Questionnaire from CRD server, it also retrieves initial values, returned by CQL. DTR saves those initial values in a temporary QuestionnaireReponse instance and then let LHC control merging Questionnaire and QuestionnaireReponse together to generate display form. Before the fix, the initial QuestionnaireReponse looks like this:
image
There are many items with empty answers before those item does not have initial value. 
This does not impact the merging since empty answer is the same as no answer. 
The only problem is it creates a huge log file with those empty answers. 
So this fix remove those items with empty answers to keep the log file smaller. So it is easier for developer to identify issues in the development process.

**Comment by lpdecelles** [comment]
When I try to launch DTR I get this blank page:

image

**Comment by yunwwang** [comment]
I addressed the merge conflict. But I could not reproduce that blank screen. Which patient/topic did you use?

**Comment by lpdecelles** [comment]
image

William Oster

**Comment by yunwwang** [comment]
Works fine on my testing. So, try to get the latest commit. And if you get a popup for using previous saved answer, select "No" since the data schema may have been changed.

**Comment by lpdecelles** [comment]
It seems to work now. Also, I don't see the empty answers. I still have some questions about the limited pre-population. I will save that for another Jira ticket. :-)

**Pull request merged**
