### PR TITLE
cerner changes

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Some small changes that fix the major bugs that stopped DTR from working on the cerner sandbox.

The cerner sandbox doesn't provide appContext, so the app is using its default appContext

There's still a warning that I haven't figure out why it occurs, but it doesn't impede app usage.

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
I cannot recreate that bug, DTR renders fine for me.  What branches are you using?

**Comment by lpdecelles** [comment]
The cerner branch and master for the others.

**Comment by plarocque4** [comment]
I was unsuccessful as well. I am using master for all repos except for DTR where I am using the cerner branch.
Screen Shot 2020-06-11 at 8 41 44 PM

**Comment by KeeyanGhoreshi** [comment]
I've updated everything to the latest on master and I still can't recreate the bug.  I choose Vlad and use the Home Oxygen device request and it loads just fine.  Without an error I can't really figure out why this is happening.  It might just be that the elm execution is taking a very long time.  This was the case for me when testing against cerner, but I assumed it was because the patient record was massive.

**Comment by plarocque4** [comment]
With the Vlad and Home Oxygen Therapy it still gets stuck for me. I even gave it several minutes but didn't get any further than it did last night. I switched my branch for DTR back to master and the form loaded properly.

**Comment by plarocque4** [comment]
I'm not sure what is going on with this **cerner** branch, perhaps it is missing something that is needed from the master branch. I applied the changes from this branch by hand into a new branch I created off of master called **cerner2** and the form loaded without any problems when using that new branch.

**Comment by lpdecelles** [comment]
Pat I see the same thing with HOT/Vlad.

Keeyan, do you have the latest rule sets and value sets?

From CRD
gradle embedCdsLibrary

Loaded the latest value sets: 
image

**Comment by lpdecelles** [comment]
Right, so maybe a forward merge from master will fix it.

**Comment by KeeyanGhoreshi** [comment]
cerner2 doesn't work for me, failing to get valuesets with a 404.  I assume I don't have something set up with CRD.

**Comment by plarocque4** [comment]
The valuesets have to be loaded from VSAC. Instructions can be found here:
https://github.com/HL7-DaVinci/CRD/tree/master/server#using-valuesets-from-vsac

**Comment by lpdecelles** [comment]
I just use the CRD UI to load them (value sets).

**Comment by KeeyanGhoreshi** [comment]
Closing this to move the PR to #98

**Pull request closed without merging**
